"use client";

import React, { useState } from "react";
import {
  DiscoverResponse,
  PositionResponse,
  ShapeResponse,
  VisualizeResponse,
  ChallengeResponse,
  DeliverResponse
} from "../lib/api";
import {
  PackageCheck,
  Sparkles,
  Loader2,
  AlertCircle,
  Copy,
  Check,
  Rocket,
  MessageSquareText,
  Users,
  Volume2,
  Megaphone,
  Palette,
  ShieldAlert,
  ListChecks,
  Tag,
  Compass,
  ArrowUpRight,
  Layers,
  Zap,
  CheckCircle2
} from "lucide-react";

interface DeliverSectionProps {
  discoverContext: DiscoverResponse;
  positionContext: PositionResponse;
  shapeContext: ShapeResponse;
  visualizeContext: VisualizeResponse;
  challengeContext: ChallengeResponse;
  deliverData: DeliverResponse | null;
  onBuildDeliver: () => Promise<void>;
  isLoading: boolean;
  error: string | null;
  onProceedToEvaluate?: () => void;
}

export const DeliverSection: React.FC<DeliverSectionProps> = ({
  positionContext,
  shapeContext,
  deliverData,
  onBuildDeliver,
  isLoading,
  error,
  onProceedToEvaluate,
}) => {
  const [copied, setCopied] = useState(false);

  const handleCopy = () => {
    if (!deliverData) return;

    const formattedKit = `================================================
BRANDFORGE FINAL LAUNCH BRAND KIT
================================================

01. BRAND OVERVIEW
------------------
Brand Name: ${deliverData.brand_name}
One-Line Pitch: ${deliverData.one_line_pitch}
Brand Summary:
${deliverData.brand_summary}

02. CORE MESSAGING
------------------
Hero Headline: ${deliverData.hero_headline}
Hero Subheadline: ${deliverData.hero_subheadline}
Value Proposition: ${deliverData.value_proposition}
Product Description:
${deliverData.product_description}
Primary CTA: ${deliverData.primary_cta}

03. TARGET AUDIENCE & PROBLEM
-----------------------------
Audience Summary: ${deliverData.target_audience_summary}
Core Problem: ${deliverData.core_problem}

04. BRAND VOICE & PERSONALITY
-----------------------------
Tone of Voice: ${deliverData.tone_of_voice}
Brand Personality: ${deliverData.brand_personality.join(", ")}
Messaging Guidelines:
${deliverData.messaging_guidelines.map((g) => `- ${g}`).join("\n")}

05. LAUNCH COPY
---------------
Launch Announcement:
${deliverData.launch_announcement}

Social Media Posts:
${deliverData.social_media_posts.map((post, i) => `[Post ${i + 1}]\n${post}`).join("\n\n")}

06. BRAND DIRECTION & PILLARS
-----------------------------
Visual Identity Summary:
${deliverData.visual_identity_summary}

Brand Pillars:
${deliverData.key_brand_pillars.map((p) => `- ${p}`).join("\n")}

07. RISKS & MITIGATION
----------------------
Key Risks Identified:
${deliverData.key_risks.map((r) => `- ${r}`).join("\n")}

Risk Mitigation Strategy:
${deliverData.risk_mitigation_summary}

08. RECOMMENDED NEXT STEPS
--------------------------
${deliverData.next_steps.map((step, i) => `${i + 1}. ${step}`).join("\n")}

================================================
Generated by BrandForge AI Strategy Engine
================================================`;

    navigator.clipboard.writeText(formattedKit).then(() => {
      setCopied(true);
      setTimeout(() => setCopied(false), 2500);
    });
  };

  return (
    <div id="deliver-stage-section" className="w-full max-w-5xl mx-auto my-12 px-4 space-y-8 animate-fade-in">
      {/* Stage Header Banner */}
      <div className="relative overflow-hidden rounded-2xl bg-gradient-to-r from-emerald-950/90 via-slate-900 to-indigo-950/90 border border-emerald-500/40 p-6 sm:p-8 shadow-2xl">
        <div className="absolute top-0 left-0 right-0 h-1 bg-gradient-to-r from-emerald-400 via-teal-400 to-indigo-500"></div>

        <div className="flex flex-col md:flex-row items-start md:items-center justify-between gap-6">
          <div className="space-y-2 max-w-2xl">
            <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-emerald-500/10 border border-emerald-500/30 text-emerald-300 text-xs font-semibold uppercase tracking-wider">
              <PackageCheck className="w-3.5 h-3.5" />
              <span>Phase 6 — Deliver</span>
            </div>
            <h2 className="text-2xl sm:text-3xl font-extrabold text-white tracking-tight">
              Final Launch Brand Kit
            </h2>
            <p className="text-sm text-slate-300 leading-relaxed">
              Your complete launch-ready brand kit. Synthesizing positioning, verbal messaging, visual strategy, and risk mitigations into one unified brand system.
            </p>

            <div className="flex flex-wrap items-center gap-4 text-xs text-slate-300 font-mono pt-1">
              <div className="flex items-center gap-1.5 text-emerald-300">
                <CheckCircle2 className="w-3.5 h-3.5 text-emerald-400 shrink-0" />
                <span>Synthesis of Phases 1–5 Complete</span>
              </div>
              <div className="flex items-center gap-1.5 text-indigo-300">
                <Tag className="w-3.5 h-3.5 text-indigo-400 shrink-0" />
                <span>Category: <strong>{positionContext.category}</strong></span>
              </div>
              <div className="flex items-center gap-1.5 text-teal-300">
                <Compass className="w-3.5 h-3.5 text-teal-400 shrink-0" />
                <span>Tagline: <strong>"{shapeContext.tagline}"</strong></span>
              </div>
            </div>
          </div>

          <div className="w-full md:w-auto shrink-0 flex flex-col sm:flex-row gap-3">
            {!deliverData && (
              <button
                id="deliver-brand-btn"
                onClick={onBuildDeliver}
                disabled={isLoading}
                className="w-full md:w-auto px-7 py-3.5 rounded-xl font-semibold text-white bg-gradient-to-r from-emerald-600 via-teal-600 to-indigo-600 hover:from-emerald-500 hover:to-indigo-500 shadow-lg shadow-emerald-500/25 hover:shadow-emerald-500/40 hover:scale-[1.02] active:scale-[0.98] transition duration-200 flex items-center justify-center gap-2.5 cursor-pointer disabled:opacity-50 disabled:cursor-not-allowed disabled:hover:scale-100"
              >
                {isLoading ? (
                  <>
                    <Loader2 className="w-5 h-5 animate-spin" />
                    <span>Compiling Brand Kit...</span>
                  </>
                ) : (
                  <>
                    <Sparkles className="w-5 h-5 text-emerald-300" />
                    <span>Generate Final Brand Kit</span>
                  </>
                )}
              </button>
            )}

            {deliverData && (
              <button
                onClick={handleCopy}
                className="w-full md:w-auto px-6 py-3.5 rounded-xl font-semibold text-slate-100 bg-slate-800/90 hover:bg-slate-700 border border-emerald-500/40 shadow-lg hover:shadow-emerald-500/20 hover:scale-[1.02] active:scale-[0.98] transition duration-200 flex items-center justify-center gap-2 cursor-pointer"
              >
                {copied ? (
                  <>
                    <Check className="w-4 h-4 text-emerald-400" />
                    <span className="text-emerald-300">Copied to Clipboard!</span>
                  </>
                ) : (
                  <>
                    <Copy className="w-4 h-4 text-slate-300" />
                    <span>Copy Brand Kit</span>
                  </>
                )}
              </button>
            )}
          </div>
        </div>
      </div>

      {/* Error Alert */}
      {error && (
        <div className="p-4 rounded-xl bg-red-950/60 border border-red-500/50 text-red-200 flex items-start gap-3">
          <AlertCircle className="w-5 h-5 text-red-400 shrink-0 mt-0.5" />
          <div className="space-y-1">
            <h4 className="text-sm font-semibold text-red-300">Synthesis Error</h4>
            <p className="text-xs text-red-200/90 leading-relaxed">{error}</p>
          </div>
        </div>
      )}

      {/* Loading State */}
      {isLoading && (
        <div className="glass-card rounded-2xl p-10 text-center space-y-4 border border-emerald-500/30">
          <div className="inline-flex p-4 rounded-full bg-emerald-500/10 border border-emerald-500/20 text-emerald-400 animate-pulse">
            <Loader2 className="w-8 h-8 animate-spin" />
          </div>
          <div className="space-y-1">
            <h3 className="text-lg font-bold text-white">Compiling your brand strategy...</h3>
            <p className="text-xs text-slate-400 max-w-md mx-auto">
              Connecting your positioning, messaging, visual identity and risk analysis into a launch-ready Brand Kit...
            </p>
          </div>
        </div>
      )}

      {/* DELIVER RESULTS GRID */}
      {deliverData && !isLoading && (
        <div className="space-y-8 animate-fade-in">
          {/* 01 — Brand Overview */}
          <div className="glass-card rounded-2xl p-6 sm:p-8 space-y-6 border-t-2 border-t-emerald-500">
            <div className="flex items-center justify-between border-b border-slate-800 pb-4">
              <div className="flex items-center gap-2.5">
                <div className="w-8 h-8 rounded-lg bg-emerald-500/10 border border-emerald-500/20 flex items-center justify-center text-emerald-400">
                  <Rocket className="w-4 h-4" />
                </div>
                <div>
                  <h3 className="text-xl font-bold text-slate-100">01 — Brand Overview</h3>
                  <p className="text-xs text-slate-400">Definitive brand identity and core elevator pitch</p>
                </div>
              </div>
              <span className="text-xs font-mono px-3 py-1 rounded-full bg-emerald-500/10 border border-emerald-500/20 text-emerald-300 font-bold">
                Brand Kit
              </span>
            </div>

            <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
              <div className="p-5 rounded-xl bg-slate-900/80 border border-slate-800 space-y-2">
                <span className="text-xs font-mono font-bold uppercase text-emerald-400">Brand Name</span>
                <p className="text-2xl font-extrabold text-white tracking-tight">{deliverData.brand_name}</p>
              </div>

              <div className="p-5 rounded-xl bg-slate-900/80 border border-slate-800 space-y-2">
                <span className="text-xs font-mono font-bold uppercase text-emerald-400">One-Line Pitch</span>
                <p className="text-sm font-semibold text-slate-200 leading-snug">{deliverData.one_line_pitch}</p>
              </div>
            </div>

            <div className="p-5 rounded-xl bg-emerald-950/20 border border-emerald-500/20 space-y-2">
              <span className="text-xs font-mono font-bold uppercase text-emerald-300">Brand Summary</span>
              <p className="text-xs text-slate-300 leading-relaxed whitespace-pre-line">{deliverData.brand_summary}</p>
            </div>
          </div>

          {/* 02 — Core Messaging */}
          <div className="glass-card rounded-2xl p-6 sm:p-8 space-y-6 border-t-2 border-t-indigo-500">
            <div className="flex items-center gap-2.5 border-b border-slate-800 pb-4">
              <div className="w-8 h-8 rounded-lg bg-indigo-500/10 border border-indigo-500/20 flex items-center justify-center text-indigo-400">
                <MessageSquareText className="w-4 h-4" />
              </div>
              <div>
                <h3 className="text-xl font-bold text-slate-100">02 — Core Messaging</h3>
                <p className="text-xs text-slate-400">Hero copy, value proposition, description, and primary CTA</p>
              </div>
            </div>

            {/* Landing Page Hero Preview Box */}
            <div className="p-6 rounded-2xl bg-gradient-to-br from-slate-900 via-indigo-950/40 to-slate-900 border border-indigo-500/30 space-y-4">
              <div className="flex items-center gap-2 text-xs font-mono text-indigo-400 font-bold uppercase">
                <Sparkles className="w-3.5 h-3.5" />
                <span>Landing Page Hero Section Preview</span>
              </div>
              <h4 className="text-2xl sm:text-3xl font-extrabold text-white tracking-tight leading-tight">
                {deliverData.hero_headline}
              </h4>
              <p className="text-slate-300 text-sm sm:text-base leading-relaxed max-w-2xl">
                {deliverData.hero_subheadline}
              </p>
              <div className="pt-2">
                <span className="inline-flex items-center gap-2 px-6 py-3 rounded-xl font-bold text-white bg-indigo-600 hover:bg-indigo-500 shadow-md transition text-sm">
                  <span>{deliverData.primary_cta}</span>
                  <ArrowUpRight className="w-4 h-4" />
                </span>
              </div>
            </div>

            <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
              <div className="p-4 rounded-xl bg-slate-900/80 border border-slate-800 space-y-2">
                <span className="text-xs font-mono font-bold uppercase text-indigo-400">Value Proposition</span>
                <p className="text-xs text-slate-200 leading-relaxed">{deliverData.value_proposition}</p>
              </div>

              <div className="p-4 rounded-xl bg-slate-900/80 border border-slate-800 space-y-2">
                <span className="text-xs font-mono font-bold uppercase text-indigo-400">Product Description</span>
                <p className="text-xs text-slate-300 leading-relaxed">{deliverData.product_description}</p>
              </div>
            </div>
          </div>

          {/* 03 — Audience & Core Problem */}
          <div className="glass-card rounded-2xl p-6 sm:p-8 space-y-6 border-t-2 border-t-purple-500">
            <div className="flex items-center gap-2.5 border-b border-slate-800 pb-4">
              <div className="w-8 h-8 rounded-lg bg-purple-500/10 border border-purple-500/20 flex items-center justify-center text-purple-400">
                <Users className="w-4 h-4" />
              </div>
              <div>
                <h3 className="text-xl font-bold text-slate-100">03 — Target Audience & Core Problem</h3>
                <p className="text-xs text-slate-400">Persona definition and essential problem statement solved</p>
              </div>
            </div>

            <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
              <div className="p-5 rounded-xl bg-slate-900/80 border border-slate-800 space-y-2">
                <span className="text-xs font-mono font-bold uppercase text-purple-400">Target Audience Persona</span>
                <p className="text-xs text-slate-200 leading-relaxed">{deliverData.target_audience_summary}</p>
              </div>

              <div className="p-5 rounded-xl bg-slate-900/80 border border-slate-800 space-y-2">
                <span className="text-xs font-mono font-bold uppercase text-purple-400">Core Problem Solved</span>
                <p className="text-xs text-slate-200 leading-relaxed">{deliverData.core_problem}</p>
              </div>
            </div>
          </div>

          {/* 04 — Brand Voice & Personality */}
          <div className="glass-card rounded-2xl p-6 sm:p-8 space-y-6 border-t-2 border-t-amber-500">
            <div className="flex items-center gap-2.5 border-b border-slate-800 pb-4">
              <div className="w-8 h-8 rounded-lg bg-amber-500/10 border border-amber-500/20 flex items-center justify-center text-amber-400">
                <Volume2 className="w-4 h-4" />
              </div>
              <div>
                <h3 className="text-xl font-bold text-slate-100">04 — Brand Voice & Guidelines</h3>
                <p className="text-xs text-slate-400">Communication tone, personality traits, and copywriting rules</p>
              </div>
            </div>

            <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
              <div className="p-5 rounded-xl bg-slate-900/80 border border-slate-800 space-y-3">
                <span className="text-xs font-mono font-bold uppercase text-amber-400">Tone of Voice</span>
                <p className="text-xs text-slate-300 leading-relaxed">{deliverData.tone_of_voice}</p>

                <div className="pt-2 space-y-1">
                  <span className="text-[11px] font-mono font-bold uppercase text-slate-400">Brand Personality Traits</span>
                  <div className="flex flex-wrap gap-1.5">
                    {deliverData.brand_personality.map((trait, idx) => (
                      <span key={idx} className="px-2.5 py-1 rounded-md text-xs font-semibold bg-amber-950/60 border border-amber-500/30 text-amber-300">
                        {trait}
                      </span>
                    ))}
                  </div>
                </div>
              </div>

              <div className="p-5 rounded-xl bg-slate-900/80 border border-slate-800 space-y-3">
                <span className="text-xs font-mono font-bold uppercase text-amber-400">Messaging & Voice Guidelines</span>
                <ul className="space-y-2">
                  {deliverData.messaging_guidelines.map((guide, idx) => (
                    <li key={idx} className="text-xs text-slate-300 flex items-start gap-2">
                      <span className="text-amber-400 font-bold">•</span>
                      <span>{guide}</span>
                    </li>
                  ))}
                </ul>
              </div>
            </div>
          </div>

          {/* 05 — Launch Copy */}
          <div className="glass-card rounded-2xl p-6 sm:p-8 space-y-6 border-t-2 border-t-teal-500">
            <div className="flex items-center gap-2.5 border-b border-slate-800 pb-4">
              <div className="w-8 h-8 rounded-lg bg-teal-500/10 border border-teal-500/20 flex items-center justify-center text-teal-400">
                <Megaphone className="w-4 h-4" />
              </div>
              <div>
                <h3 className="text-xl font-bold text-slate-100">05 — Launch Copy Assets</h3>
                <p className="text-xs text-slate-400">Ready-to-use launch announcement and social media posts</p>
              </div>
            </div>

            <div className="p-5 rounded-xl bg-slate-900/90 border border-slate-800 space-y-2">
              <span className="text-xs font-mono font-bold uppercase text-teal-400">Product Launch Announcement</span>
              <p className="text-xs text-slate-200 leading-relaxed whitespace-pre-line">{deliverData.launch_announcement}</p>
            </div>

            <div className="space-y-3">
              <span className="text-xs font-mono font-bold uppercase text-teal-400">Launch Social Media Posts</span>
              <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                {deliverData.social_media_posts.map((post, idx) => (
                  <div key={idx} className="p-4 rounded-xl bg-slate-900/80 border border-teal-500/20 space-y-2">
                    <span className="text-[11px] font-mono font-bold text-teal-300">Post #{idx + 1}</span>
                    <p className="text-xs text-slate-300 leading-relaxed whitespace-pre-line">{post}</p>
                  </div>
                ))}
              </div>
            </div>
          </div>

          {/* 06 — Brand Direction & Pillars */}
          <div className="glass-card rounded-2xl p-6 sm:p-8 space-y-6 border-t-2 border-t-cyan-500">
            <div className="flex items-center gap-2.5 border-b border-slate-800 pb-4">
              <div className="w-8 h-8 rounded-lg bg-cyan-500/10 border border-cyan-500/20 flex items-center justify-center text-cyan-400">
                <Palette className="w-4 h-4" />
              </div>
              <div>
                <h3 className="text-xl font-bold text-slate-100">06 — Brand Direction & Pillars</h3>
                <p className="text-xs text-slate-400">Visual identity synthesis and strategic brand pillars</p>
              </div>
            </div>

            <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
              <div className="p-5 rounded-xl bg-slate-900/80 border border-slate-800 space-y-2">
                <span className="text-xs font-mono font-bold uppercase text-cyan-400">Visual Identity Direction</span>
                <p className="text-xs text-slate-300 leading-relaxed">{deliverData.visual_identity_summary}</p>
              </div>

              <div className="p-5 rounded-xl bg-slate-900/80 border border-slate-800 space-y-2">
                <span className="text-xs font-mono font-bold uppercase text-cyan-400">Key Brand Pillars</span>
                <div className="space-y-2 pt-1">
                  {deliverData.key_brand_pillars.map((pillar, idx) => (
                    <div key={idx} className="flex items-center gap-2 text-xs text-slate-200">
                      <span className="w-5 h-5 rounded bg-cyan-500/20 text-cyan-300 font-mono text-[11px] font-bold flex items-center justify-center shrink-0">
                        {idx + 1}
                      </span>
                      <span>{pillar}</span>
                    </div>
                  ))}
                </div>
              </div>
            </div>
          </div>

          {/* 07 — Risks & Mitigation */}
          <div className="glass-card rounded-2xl p-6 sm:p-8 space-y-6 border-t-2 border-t-rose-500">
            <div className="flex items-center gap-2.5 border-b border-slate-800 pb-4">
              <div className="w-8 h-8 rounded-lg bg-rose-500/10 border border-rose-500/20 flex items-center justify-center text-rose-400">
                <ShieldAlert className="w-4 h-4" />
              </div>
              <div>
                <h3 className="text-xl font-bold text-slate-100">07 — Risk Audit & Mitigation</h3>
                <p className="text-xs text-slate-400">Key vulnerabilities identified and strategic defense mechanisms</p>
              </div>
            </div>

            <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
              <div className="p-5 rounded-xl bg-slate-900/80 border border-rose-500/20 space-y-2">
                <span className="text-xs font-mono font-bold uppercase text-rose-400">Key Strategic Risks</span>
                <ul className="space-y-2">
                  {deliverData.key_risks.map((risk, idx) => (
                    <li key={idx} className="text-xs text-slate-300 flex items-start gap-2">
                      <span className="text-rose-400 font-bold">•</span>
                      <span>{risk}</span>
                    </li>
                  ))}
                </ul>
              </div>

              <div className="p-5 rounded-xl bg-rose-950/20 border border-rose-500/20 space-y-2">
                <span className="text-xs font-mono font-bold uppercase text-rose-300">Risk Mitigation Strategy</span>
                <p className="text-xs text-slate-300 leading-relaxed">{deliverData.risk_mitigation_summary}</p>
              </div>
            </div>
          </div>

          {/* 08 — Recommended Next Steps */}
          <div className="glass-card rounded-2xl p-6 sm:p-8 space-y-6 border-t-2 border-t-emerald-400">
            <div className="flex items-center gap-2.5 border-b border-slate-800 pb-4">
              <div className="w-8 h-8 rounded-lg bg-emerald-500/10 border border-emerald-500/20 flex items-center justify-center text-emerald-400">
                <ListChecks className="w-4 h-4" />
              </div>
              <div>
                <h3 className="text-xl font-bold text-slate-100">08 — Actionable Next Steps</h3>
                <p className="text-xs text-slate-400">Immediate launch execution roadmap</p>
              </div>
            </div>

            <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
              {deliverData.next_steps.map((step, idx) => (
                <div key={idx} className="p-4 rounded-xl bg-slate-900/80 border border-emerald-500/20 flex items-start gap-3">
                  <div className="w-6 h-6 rounded-full bg-emerald-500/20 text-emerald-300 font-mono text-xs flex items-center justify-center shrink-0 mt-0.5 font-bold">
                    {idx + 1}
                  </div>
                  <p className="text-xs text-slate-200 leading-relaxed font-medium">{step}</p>
                </div>
              ))}
            </div>
          </div>

          {/* CTA to Phase 7 Evaluate */}
          {onProceedToEvaluate && (
            <div className="pt-4 flex justify-center">
              <button
                onClick={onProceedToEvaluate}
                className="px-8 py-4 rounded-xl font-bold text-white bg-gradient-to-r from-blue-600 via-indigo-600 to-cyan-600 hover:from-blue-500 hover:to-cyan-500 shadow-xl shadow-blue-500/20 hover:shadow-blue-500/35 hover:scale-105 active:scale-95 transition duration-200 flex items-center gap-3 cursor-pointer"
              >
                <span>Proceed to Phase 7: Evaluate (Consistency Audit)</span>
                <ArrowUpRight className="w-5 h-5" />
              </button>
            </div>
          )}
        </div>
      )}
    </div>
  );
};
